(define (problem BLOCKS-14-1)
(:domain BLOCKS)
(:objects K A F L D B M E J N H I C G )
(:INIT (CLEAR N) (ONTABLE B)
(ON N G) (ON G J) (ON J C) (ON C E) (ON E I) (ON I D)
 (ON D L) (ON L M) (ON M H) (ON H F) (ON F A) (ON A K) (ON K B) (HANDEMPTY))
(:goal (AND (ON J D) (ON D B) (ON B H) (ON H M) (ON M K) (ON K F) (ON F G)
            (ON G A) (ON A I) (ON I E) (ON E L) (ON L N) (ON N C)))
)
